#if !canImport(ObjectiveC)
import XCTest

extension CPIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CPIOTests = [
        ("testCPIO", testCPIO),
        ("testMagic", testMagic),
    ]
}

extension ErrnoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrnoTests = [
        ("testEAGAIN_IS_EWOULDBLOCK", testEAGAIN_IS_EWOULDBLOCK),
        ("testELAST", testELAST),
        ("testENOTSUP_IS_EOPNOTSUPP", testENOTSUP_IS_EOPNOTSUPP),
        ("testErrno", testErrno),
    ]
}

extension PThreadSpecificTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PThreadSpecificTests = [
        ("testPThreadSpecificMax", testPThreadSpecificMax),
    ]
}

extension UnistdFunctionConstantsPathconfNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnistdFunctionConstantsPathconfNameTests = [
        ("testPathconfNameCount", testPathconfNameCount),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CPIOTests.__allTests__CPIOTests),
        testCase(ErrnoTests.__allTests__ErrnoTests),
        testCase(PThreadSpecificTests.__allTests__PThreadSpecificTests),
        testCase(UnistdFunctionConstantsPathconfNameTests.__allTests__UnistdFunctionConstantsPathconfNameTests),
    ]
}
#endif
