included:
    - ./Sources
    - ./Tests

opt_in_rules:
    - anyobject_protocol
    - array_init
    - attributes
    - contains_over_first_not_nil
    - convenience_type
    - empty_count
    - empty_string
    - explicit_init
    - fatal_error_message
    - first_where
    - for_where
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - nslocalizedstring_key
    - object_literal
    - overridden_super_call
    - prohibited_interface_builder
    - prohibited_super_call
    - reduce_into
    - redundant_type_annotation
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - trailing_closure
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces

disabled_rules:
    - cyclomatic_complexity
    - file_length
    - force_cast
    - force_try
    - function_body_length
    - generic_type_name
    - identifier_name
    - large_tuple
    - line_length
    - nesting
    - todo
    - trailing_comma
    - type_body_length
