disabled_rules:
    - identifier_name
    - line_length
    - force_cast
    - mark
    - large_tuple
    - type_body_length
    - nesting
    - file_length
    - todo
    - trailing_comma
    - function_body_length
    - cyclomatic_complexity
excluded:
    - Submodules
