language: objective-c

dist: xenial
osx_image: xcode10.1

matrix:
  include:
    - os: osx
      env:
        - NAME="Swiftlint"
          RUN_TESTS=False
          USE_XCODE_BUILD=False

    - os: osx
      env:
        - NAME="SwiftPM"
          RUN_TESTS=True
          USE_XCODE_BUILD=False

    - os: linux
      env:
        - NAME="SwiftPM"
          RUN_TESTS=True
          USE_XCODE_BUILD=False

    - os: osx
      env:
        - NAME="iOS"
          RUN_TESTS=True
          USE_XCODE_BUILD=True
          DESTINATION="OS=12.0,name=iPhone X"
          SDK="iphonesimulator"

    - os: osx
      env:
        - NAME="macOS"
          RUN_TESTS="YES"
          USE_XCODE_BUILD=True
          DESTINATION="arch=x86_64"
          SDK="macosx"

    - os: osx
      env:
        - NAME="tvOS"
          RUN_TESTS=True
          USE_XCODE_BUILD=True
          DESTINATION="OS=12.0,name=Apple TV 4K"
          SDK="appletvsimulator"

    - os: osx
      env:
        - NAME="watchOS"
          RUN_TESTS=False
          USE_XCODE_BUILD=True
          DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"
          SDK="watchsimulator"

script:
  - ./.travis-ci.sh

before_install:
  - ./.travis-ci-before-install.sh
