name: SwiftPM Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      env:
        SWIFT_VERSION: 5.1.3
        OS_VERSION_SHORT: ubuntu1804
        OS_VERSION_FULL: ubuntu18.04
      run:
        wget -q -O - https://swift.org/keys/all-keys.asc | sudo gpg --import -;
        wget https://swift.org/builds/swift-${SWIFT_VERSION}-release/${OS_VERSION_SHORT}/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-${OS_VERSION_FULL}.tar.gz;
        tar xzf swift-${SWIFT_VERSION}-RELEASE-${OS_VERSION_FULL}.tar.gz -C . --strip-components=1;
    - name: Build
      run:
        /usr/bin/swift build -v
    - name: Run tests
      run:
        /usr/bin/swift test -v
